pool:
  name: Hosted Windows 2019 with VS2019
steps:
  - task: PowerShell@2
    displayName: 'Build and Test'
    inputs:
      targetType: filePath
      filePath: ./build.ps1
      arguments: '-Target Build-CI'
